---
# This is a manually triggered workflow to build and publish documentation pages
# from the specified Git revision to GitHub pages on
# https://software-clinic.github.io/kube-security-manager/.
name: Publish documentation

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to deploy, e.g. v0.0.1
        required: true
        default: main

# Disable permissions granted to the GITHUB_TOKEN for all the available scopes.
permissions: { }

jobs:
  publish-docs:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09  # v2.5.1
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4.7.0
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material
          pip install mkdocs-macros-plugin
      - run: |
          git config user.name "danielpacak"
          git config user.email "pacak.daniel@gmail.com"
      - run: |
          mkdocs gh-deploy --force
